### PR TITLE
Added a bunch of new actions

### PR DESCRIPTION
**Pull request by gcordalis**
_Please delete all sections in italics before submitting this PR._

**Checks**

- [x] I've checked there are no linting errors.
- [? ] I've checked the code is still at 100% test coverage.

**Added Actions (if relevant)**

- Add to Reading List
- Airdrop
- Clear Up Next
- Correct Spelling
- Delete Photos
- Detect Language
- Expand URL
- Get Diffbot Article from Web Page
- Get Clipboard
- Get Contents of Web Page
- Get Current Song
- Get Frames from Image
- Get Headers of URL
- Get Images from Input
- Get Last Import
- Get Markdown from Rich Text
- Get Name of Emoji
- Get Rich Text from HTML
- Get Rich Text from Markdown
- Get Text from Input
- Get URLs from Input
- Open URL
- Play Sound
- Scan QR/Barcode
- Share
- Share with Extensions
- Show Definition
- Show In iTunes Store
- Trim Media

**Are you happy to be listed as a contributor on [Shortcuts.fun](https://shortcuts.fun)?**

_Yes_ 

**Any other information / comments**

Being my first time adding new actions wanted to check on this and see what I've missed from the below:

```
--------------------------------|----------|----------|----------|----------|-------------------|
File                            |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------------------|----------|----------|----------|----------|-------------------|
All files                       |    98.72 |      100 |    93.08 |      100 |                   |
 src                            |      100 |      100 |      100 |      100 |                   |
  index.ts                      |      100 |      100 |      100 |      100 |                   |
  variables.ts                  |      100 |      100 |      100 |      100 |                   |
 src/actions                    |    98.44 |      100 |    90.63 |      100 |                   |
  addToReadingList.ts           |      100 |      100 |      100 |      100 |                   |
  addToVariable.ts              |      100 |      100 |      100 |      100 |                   |
  airdropDocument.ts            |      100 |      100 |      100 |      100 |                   |
  ask.ts                        |      100 |      100 |      100 |      100 |                   |
  base64Encode.ts               |      100 |      100 |      100 |      100 |                   |
  calculate.ts                  |      100 |      100 |      100 |      100 |                   |
  calculateStatistics.ts        |      100 |      100 |      100 |      100 |                   |
  chooseFromMenu.ts             |      100 |      100 |      100 |      100 |                   |
  clearUpNext.ts                |      100 |      100 |      100 |      100 |                   |
  comment.ts                    |      100 |      100 |      100 |      100 |                   |
  conditional.ts                |      100 |      100 |      100 |      100 |                   |
  continueShortcutInApp.ts      |      100 |      100 |      100 |      100 |                   |
  correctSpelling.ts            |      100 |      100 |      100 |      100 |                   |
  count.ts                      |      100 |      100 |      100 |      100 |                   |
  deletePhotos.ts               |      100 |      100 |      100 |      100 |                   |
  detectLanguage.ts             |      100 |      100 |      100 |      100 |                   |
  exitShortcut.ts               |      100 |      100 |      100 |      100 |                   |
  expandURL.ts                  |      100 |      100 |      100 |      100 |                   |
  extractArchive.ts             |      100 |      100 |      100 |      100 |                   |
  generateHash.ts               |      100 |      100 |      100 |      100 |                   |
  getAddressesFromInput.ts      |      100 |      100 |      100 |      100 |                   |
  getArticle.ts                 |      100 |      100 |      100 |      100 |                   |
  getBatteryLevel.ts            |      100 |      100 |      100 |      100 |                   |
  getClipboard.ts               |      100 |      100 |      100 |      100 |                   |
  getContactsFromInput.ts       |      100 |      100 |      100 |      100 |                   |
  getContentsOfUrl.ts           |      100 |      100 |      100 |      100 |                   |
  getContentsOfWebPage.ts       |      100 |      100 |      100 |      100 |                   |
  getCurrentIpAddress.ts        |      100 |      100 |      100 |      100 |                   |
  getCurrentLocation.ts         |      100 |      100 |      100 |      100 |                   |
  getCurrentSong.ts             |    66.67 |      100 |        0 |      100 |                   |
  getDatesFromInput.ts          |      100 |      100 |      100 |      100 |                   |
  getDeviceDetails.ts           |      100 |      100 |      100 |      100 |                   |
  getDictionaryFromInput.ts     |       75 |      100 |        0 |      100 |                   |
  getDictionaryValue.ts         |      100 |      100 |      100 |      100 |                   |
  getEmailAddressesFromInput.ts |    66.67 |      100 |        0 |      100 |                   |
  getFramesFromImage.ts         |      100 |      100 |      100 |      100 |                   |
  getHeadersOfURL.ts            |      100 |      100 |      100 |      100 |                   |
  getImagesFromInput.ts         |      100 |      100 |      100 |      100 |                   |
  getLastImport.ts              |      100 |      100 |      100 |      100 |                   |
  getLinkToFile.ts              |    66.67 |      100 |        0 |      100 |                   |
  getMarkdownFromRichText.ts    |      100 |      100 |      100 |      100 |                   |
  getName.ts                    |      100 |      100 |      100 |      100 |                   |
  getNameOfEmoji.ts             |      100 |      100 |      100 |      100 |                   |
  getNetworkDetails.ts          |      100 |      100 |      100 |      100 |                   |
  getPhoneNumbersFromInput.ts   |       75 |      100 |        0 |      100 |                   |
  getRichTextFromHTML.ts        |      100 |      100 |      100 |      100 |                   |
  getTextFromInput.ts           |      100 |      100 |      100 |      100 |                   |
  getType.ts                    |      100 |      100 |      100 |      100 |                   |
  getURLsFromInput.ts           |      100 |      100 |      100 |      100 |                   |
  getVariable.ts                |      100 |      100 |      100 |      100 |                   |
  index.ts                      |      100 |      100 |      100 |      100 |                   |
  nothing.ts                    |      100 |      100 |      100 |      100 |                   |
  number.ts                     |      100 |      100 |      100 |      100 |                   |
  openInBooks.ts                |      100 |      100 |      100 |      100 |                   |
  openURL.ts                    |      100 |      100 |      100 |      100 |                   |
  pauseMusic.ts                 |      100 |      100 |      100 |      100 |                   |
  playSound.ts                  |      100 |      100 |      100 |      100 |                   |
  print.ts                      |      100 |      100 |      100 |      100 |                   |
  quickLook.ts                  |      100 |      100 |      100 |      100 |                   |
  randomNumber.ts               |      100 |      100 |      100 |      100 |                   |
  removeReminders.ts            |       75 |      100 |        0 |      100 |                   |
  runScriptOverSSH.ts           |      100 |      100 |      100 |      100 |                   |
  runShortcut.ts                |      100 |      100 |      100 |      100 |                   |
  scanBarcode.ts                |      100 |      100 |      100 |      100 |                   |
  selectEmailAddress.ts         |    66.67 |      100 |        0 |      100 |                   |
  selectPhoneNumber.ts          |       75 |      100 |        0 |      100 |                   |
  setAirplaneMode.ts            |      100 |      100 |      100 |      100 |                   |
  setBluetooth.ts               |      100 |      100 |      100 |      100 |                   |
  setBrightness.ts              |      100 |      100 |      100 |      100 |                   |
  setCellularData.ts            |      100 |      100 |      100 |      100 |                   |
  setDoNotDisturb.ts            |      100 |      100 |      100 |      100 |                   |
  setLowPowerMode.ts            |      100 |      100 |      100 |      100 |                   |
  setName.ts                    |      100 |      100 |      100 |      100 |                   |
  setTorch.ts                   |      100 |      100 |      100 |      100 |                   |
  setVariable.ts                |      100 |      100 |      100 |      100 |                   |
  setVolume.ts                  |      100 |      100 |      100 |      100 |                   |
  setWiFi.ts                    |      100 |      100 |      100 |      100 |                   |
  share.ts                      |      100 |      100 |      100 |      100 |                   |
  shareWithExtensions.ts        |      100 |      100 |      100 |      100 |                   |
  showAlert.ts                  |      100 |      100 |      100 |      100 |                   |
  showDefinition.ts             |      100 |      100 |      100 |      100 |                   |
  showInCalendar.ts             |       75 |      100 |        0 |      100 |                   |
  showInItunesStore.ts          |      100 |      100 |      100 |      100 |                   |
  showNotification.ts           |      100 |      100 |      100 |      100 |                   |
  showResult.ts                 |      100 |      100 |      100 |      100 |                   |
  skipBack.ts                   |      100 |      100 |      100 |      100 |                   |
  skipForward.ts                |      100 |      100 |      100 |      100 |                   |
  text.ts                       |      100 |      100 |      100 |      100 |                   |
  trimMedia.ts                  |      100 |      100 |      100 |      100 |                   |
  url.ts                        |      100 |      100 |      100 |      100 |                   |
  vibrateDevice.ts              |      100 |      100 |      100 |      100 |                   |
  viewContentGraph.ts           |      100 |      100 |      100 |      100 |                   |
  wait.ts                       |      100 |      100 |      100 |      100 |                   |
  waitToReturn.ts               |      100 |      100 |      100 |      100 |                   |
 src/meta                       |      100 |      100 |      100 |      100 |                   |
  colors.ts                     |      100 |      100 |      100 |      100 |                   |
  glyphs.ts                     |      100 |      100 |      100 |      100 |                   |
  index.ts                      |      100 |      100 |      100 |      100 |                   |
 src/utils                      |      100 |      100 |      100 |      100 |                   |
  actionOutput.ts               |      100 |      100 |      100 |      100 |                   |
  buildSerialization.ts         |      100 |      100 |      100 |      100 |                   |
  buildShortcut.ts              |      100 |      100 |      100 |      100 |                   |
  buildShortcutTemplate.ts      |      100 |      100 |      100 |      100 |                   |
  encodeShortcut.ts             |      100 |      100 |      100 |      100 |                   |
  flatten.ts                    |      100 |      100 |      100 |      100 |                   |
  getItemType.ts                |      100 |      100 |      100 |      100 |                   |
  index.ts                      |      100 |      100 |      100 |      100 |                   |
  variable.ts                   |      100 |      100 |      100 |      100 |                   |
  withActionOutput.ts           |      100 |      100 |      100 |      100 |                   |
  withVariables.ts              |      100 |      100 |      100 |      100 |                   |
--------------------------------|----------|----------|----------|----------|-------------------|
```

### CODE REVIEW

**Comment by joshfarrant** [comment]
Wow, that's a lot of actions! 🤩

Thanks @gcordalis! I'll take a look at the tests for you 👍

**Comment by gcordalis** [comment]
I'm not 100% sure how the withActionOutput's will go. I planned to avoid them for this batch but left a few in.

If there's anything I can change/fix up please let me know :)

**Comment by xAlien95** [comment]
@gcordalis, AirDrop has already been added in #49 😉

**Comment by joshfarrant** [comment]
I'm looking at this now, I'll update the branch with any required changes.

**Comment by joshfarrant** [comment]
Right, I've got this a bit closer to being ready now. @gcordalis Take a look at 207c169d86746b66ed886d22cb9b065b212f56b0 and the [gcordalis-master branch](https://github.com/joshfarrant/shortcuts-js/commits/gcordalis-master).

I've modified a few files (mostly names and documentation comments) and those changes are in that branch. The files that are in this PR that aren't in that branch are

```
	src/actions/getCurrentLocation.ts
	src/actions/getDictionaryFromInput.ts
	src/actions/getEmailAddressesFromInput.ts
	src/actions/getLinkToFile.ts
	src/actions/getPhoneNumbersFromInput.ts
	src/actions/removeReminders.ts
	src/actions/selectEmailAddress.ts
	src/actions/selectPhoneNumber.ts
	src/actions/showInCalendar.ts
```

I've also removed the references to those files from `src/actions/index.js`, however there may still be references to them in the `WFWorkflowActionIdentifiers` file, as I didn't fancy going through that and checking each individually, but don't worry about that.

I'm more than happy to merge the `gcordalis-master` branch into master in its current state (although I have just had an email from Travis, so I'll take a look at that).

**Comment by gcordalis** [comment]
@joshfarrant thanks for checking this out. 

I’ll smash out the tests that are missing today and submit a PR for this fork. 

I’m so sad that I missed those curly braces... I thought I was thorough with my checks!

**Comment by joshfarrant** [comment]
Just as a side-note, this PR has rocketed us up to just under 30% of all built-in actions implemented 🎉 🚀

https://shortcuts.fun/

And that's not even counting the actions which are added but not yet tested.

**Pull request merged**
