### PR TITLE
Repeat action

### PR DESCRIPTION
**Pull request by lee-hyunkyu**
_Please delete all sections in italics before submitting this PR._

**Added Actions (if relevant)**

- Repeat

**Are you happy to be listed as a contributor on [Shortcuts.fun](https://shortcuts.fun)?**

_Yes_

**Any other information / comments**

As a newcomer to javascript and typescript, I was stuck for a while on how to run the tests. It may be useful to add the command `yarn test` to the Contributing Guide. Otherwise the guide was very helpful.

### CODE REVIEW

**Comment by xAlien95** [comment]
@lee-hyunkyu, thank you for tackling this action! Unlike the others, this one is particular since it has unique properties, such as the `Repeat Index` "local variable":

repeat

That's something to look for with a little more caution; also, the `repeat` action should be capable of been nested multiple times, so a simple `repeatIndex` variable on the line of `clipboard`, `askWhenRun`, `currentDate` and `shortcutInput` couldn't be enough.

It has also to be noted that this action can have an actionOutput, so I suggest to enclose it in `withActionOutput` at the end of the .ts file.

As a final suggestion regarding the [missing test at line 34](https://travis-ci.org/joshfarrant/shortcuts-js/jobs/473180752): we usually don't force correctness on parameters, so at lines 33 and 34

https://github.com/joshfarrant/shortcuts-js/blob/dfd520f5b5f8893d828ef15bec4e1592647f722a/src/actions/repeat.ts#L33-L34

you could simply write

```ts
WFRepeatCount: count,
```

Beside that, I really like this initial implementation. Thank you again!

If you have questions about the implementation of the "Repeat Index" local variable, feel free to ask.
As for the comment you provided, you can run tests locally with

```
npm run test
```

You can even use a watcher using

```
npm run test:watch
```

**Comment by lee-hyunkyu** [comment]
@xAlien95 Thanks for the feedback

I'll get started on adding support for the actionOutput. 

As for the Repeat Index, I thought the following would be the way to use them. 
img_5cc970857123-1

Therefore, for the above, the following code can implement the shortcut using repeat variables. 

```js
const innerRepeatSubactions = [
  showAlert({
    message: {
      Value: {
        string: "Do you want to continue? \n￼￼",
        attachmentsByRange: {
          '{26, 1}': {
            VariableName: 'Repeat Index',
            Type: 'Variable'
          },
          '{27, 1}': {
            VariableName: 'Repeat Index 2',
            Type: 'Variable'
          },
        }
      },
      WFSerializationType: 'WFTextTokenString'
    }
  }),
]
const innerRepeatAction = repeat({
  count: 6,
  actions: innerRepeatSubactions
});

const outerRepeatSubactions = [
  repeatAction
];
const outerRepeatAction = repeat({
  count: 12,
  actions: outerRepeatSubactions
});

const actions = [
  outerRepeatSubactions
];

const shortcut = buildShortcut(actions);
```

Is there another implementation that you had in mind?

**Comment by lee-hyunkyu** [comment]
Some notes about this new commit. There are some changes made to the `withActionOutput.ts` file that may need to be reviewed. The changes were made as currently the `withActionOutput` only supported actions that had one WFWorkflowAction. With repeat, however, the action objects were made up of a list of WFWorkflowActions. Additional tests were included in the withActionOutput file to ensure that the changes actual work.

**Comment by xAlien95** [comment]
> There are some changes made to the withActionOutput.ts file that may need to be reviewed. The changes were made as currently the withActionOutput only supported actions that had one WFWorkflowAction. With repeat, however, the action objects were made up of a list of WFWorkflowActions. Additional tests were included in the withActionOutput file to ensure that the changes actual work.

Thank you for looking into that aspect. `conditional()` and `choooseFromMenu()` actions need that addition too. However, I would suggest writing it like this:

```ts
export const withActionOutput = <OptionsType>(
  actionBuilder: (options: OptionsType) => WFWorkflowAction | WFWorkflowAction[],
) => (
  (
    options: OptionsType,
    output?: Variable,
  ): WFWorkflowAction | WFWorkflowAction[] => {
    const action = actionBuilder(options);

    if (output) {
      if (!Array.isArray(action)) {
        action.WFWorkflowActionParameters.UUID = output.Value.OutputUUID;
        if (output.Value.OutputName) {
          action.WFWorkflowActionParameters.CustomOutputName = output.Value.OutputName;
        }
      } else {
        const last = action[action.length - 1];
        last.WFWorkflowActionParameters.UUID = output.Value.OutputUUID;
        if (output.Value.OutputName) {
          last.WFWorkflowActionParameters.CustomOutputName = output.Value.OutputName;
        }
      }
    }
    return action;
  }
);
```

TypeScript is smart enough to know that in a `Array.isArray()` conditional block, the `action` variable is of type `WFWorkflowAction[]`, so we don't need redundant type coercions. Also, looks like the `UUID`s are applied only on the last action, so you don't need to edit the first one too.

I would also add a `repeatIndex()` variable in `src/variables.ts` (or somewhere else?), like this:

```ts
import Variable from './interfaces/Variable';

const askWhenRun: Variable = new Variable({
  Type: 'Ask',
});

const clipboard: Variable = new Variable({
  Type: 'Clipboard',
});

const currentDate: Variable = new Variable({
  Type: 'CurrentDate',
});

const shortcutInput: Variable = new Variable({
  Type: 'ExtensionInput',
});

const repeatIndex = (
  level?: number,
): Variable => new Variable({
  VariableName: `Repeat Index${
    level && level !== 1 && ` ${level}`
  }`,
  Type: 'Variable',
});

export {
  askWhenRun,
  clipboard,
  currentDate,
  repeatIndex,
  shortcutInput,
};
```

This way, [your suggested example](https://github.com/joshfarrant/shortcuts-js/pull/60#issuecomment-450451307) will become:

```js
const actions = [
  repeat({
    count: 12,
    actions: [
      repeat({
        count: 6,
        actions: [
          showAlert({
            message: withVariables`Do you want to continue?\n${repeatIndex()}${repeatIndex(2)}`,
          }),
        ],
      }),
    ],
  }),
];
```

@joshfarrant, what are your thoughts on this?

**Comment by lee-hyunkyu** [comment]
Suggestions implemented with new tests added in appropriate places.

**Comment by joshfarrant** [comment]
I've started merging this in, with a few minor tweaks. Take a look at https://github.com/joshfarrant/shortcuts-js/commit/fc6c43a3325058481b1cf6db9671aa4933f5dfad.

The main changes I've made to the current implementation are:
- Extract `compareObjectsWithGroupingIdentifier` into it's own file to prevent further duplication.
- Add `withActionOutput` to `conditional` and `chooseFromMenu` actions.
- Remove the need to cast types [here](https://github.com/joshfarrant/shortcuts-js/pull/60/files#diff-360d466008907b2b13158b96c3bd9d73R49) and in a few other places.

So nothing major really - other than that it looks good, thanks for the work @lee-hyunkyu!

Let me know if either of you have any thoughts before this is merged.

**Comment by xAlien95** [comment]
Awesome, thanks @joshfarrant!

I was thinking about the `conditional()` action:

https://github.com/joshfarrant/shortcuts-js/blob/fc6c43a3325058481b1cf6db9671aa4933f5dfad/src/actions/conditional.ts#L41-L64

Both `input` and `value` parameters are optionals but without a default value. In the app the default values are respectively "Contains" and "example". Should we add them?

Also, I think we could remove the empty string `''` from `conditionMap` at line 9, since the default value in the app is "Contains".

https://github.com/joshfarrant/shortcuts-js/blob/fc6c43a3325058481b1cf6db9671aa4933f5dfad/src/actions/conditional.ts#L8-L14

**Comment by joshfarrant** [comment]
Sounds good, will take a look 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joshfarrant** [comment]
@lee-hyunkyu I can only apologise for taking so long to merge this - thank you so much for your work on it!

**Pull request merged**
