### PR TITLE
new way of exporting the shortcuts

### PR DESCRIPTION
**Pull request by rlb222**
I changed step 2 to reflect the solution in issue #217.
I also provided a new shortcut (url) with email capability

**Checks**

- [x] I've checked there are no linting errors.
- [x] I've checked the code is still at 100% test coverage.

**Added Actions (if relevant)**

**Are you happy to be listed as a contributor on [Shortcuts.fun](https://shortcuts.fun)?**

_Yes_ 

**Any other information / comments**

### CODE REVIEW

**Review by KilianKilmister — APPROVED** [review]

**Comment by KilianKilmister** [comment]
Why hasn't this been merged yet?, just found the project and ran directly into the issue

**Comment by rlb222** [comment]
Is this something I should do, as the owner of the pull request?
I’m sorry I’m not familiar with the procedure. 

René 

—/—

**Comment by KilianKilmister** [comment]
@rlb222 No need to apologize. No it's not up to you. this has to be done by someone with **push**-access to the repo. I'm just wondering why this hasn't been merged.

**Comment by rlb222** [comment]
Thanks!
And I’m wondering as well 🙂 now. 

René 

—/—

**Comment by joshfarrant** [comment]
Yep! It's only my lack of diligence that's prevented this from being merged! I've not given the repo the care it deserves of late.

When I'm next with my laptop I'll get this merged in, that will be early next week.

**Comment by pvinis** [comment]
👀

**Comment by 0xdevalias** [comment]
> > You may also find some benefit in something like this:
> > 
> > - https://routinehub.co/shortcut/5256/
> >   - > Shortcut Source Tool: View, convert, save source in plist or json, edit and import back to Shortcuts, review in browser
> > 
> > _Originally posted by @0xdevalias in https://github.com/joshfarrant/shortcuts-js/issues/683#issuecomment-1548831442_
> 
> > Looking a little closer at that shortcut, the main bit of functionality seems to basically be modifying the iCloud Share URL slightly:
> > 
> > Given a URL like this:
> > 
> > ```
> > https://www.icloud.com/shortcuts/ABC12
> > ```
> > 
> > It becomes:
> > 
> > ```
> > https://www.icloud.com/shortcuts/api/records/ABC123
> > ```
> > 
> > Then extracts the following from the JSON on that page:
> > 
> > - the URL for the unsigned shortcut file (which is an 'Apple binary property list' file): `fields -> shortcut -> value -> downloadURL`
> > - the name of the shortcut workflow: `fields -> name -> value`
> > 
> > We can then convert that binary plist file to XML or JSON using `plutil` (though when I tried the JSON format I got an error (`invalid object in plist for destination format`), so might have to stick to XML):
> > 
> > ```shell
> > plutil -convert xml1 -e plist.xml -- the-downloaded-shortcut.plist
> > ```
> > 
> > or
> > 
> > ```
> > plutil -convert json -e plist.json -- the-downloaded-shortcut.plist
> > ```
> > _(Crossposted: https://www.reddit.com/r/shortcuts/comments/13h61hv/comment/jl4dw28/)_
> > 
> > _Originally posted by @0xdevalias in https://github.com/joshfarrant/shortcuts-js/issues/683#issuecomment-1556546326_
> 
> _Originally posted by @0xdevalias in https://github.com/joshfarrant/shortcuts-js/issues/217#issuecomment-1556564018_

**Pull request closed without merging**
