### PR TITLE
 Variables: added property aggrandizement

### PR DESCRIPTION
**Pull request by xAlien95**
**Checks**

- [x] I've checked there are no linting errors.
- [x] I've checked the code is still at 100% test coverage.

**Added Actions (if relevant)**

- None

**Are you happy to be listed as a contributor on [Shortcuts.fun](https://shortcuts.fun)?**

Yes

**Any other information / comments**

This pull request follows the variables refactoring done in #14 and #47 and adds full support for aggrandizements. Specifically, you can now use the `get` parameter to access properties of a coerced type:

picsew_3ab4

```ts
clipboard.with({
  type: 'App Store app',
  get: 'Store URL',
})
```

### CODE REVIEW

**Comment by joshfarrant** [comment]
Looks fantastic!

**Comment by vergenzt** [comment]
Just out of curiosity... do you recall how you derived these `PropertyUserInfo` values? 🙂 I'm working on a bit of Shortcuts scripting myself, and was wondering whether you had some automated means of extracting them or if you uncovered them manually by tapping through the various option and exporting each.

**Comment by xAlien95** [comment]
> was wondering whether you had some automated means of extracting them or if you uncovered them manually by tapping through the various option and exporting each.

@vergenzt, the latter. Unfortunately, since 3rd party apps can now integrate their own custom types, there would be no easy way of obtaining all the possible `AggrandizementCoercionItemClass`es without manually installing those apps. As an example, the [Charty](https://apps.apple.com/us/app/charty-for-shortcuts/id1494386093) app provides a "Charty Data Set" result type with its own accessible properties.

**Comment by vergenzt** [comment]
Makes sense. Thanks for the quick response!!

**Pull request merged**
